/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModuleRequest
 */
export interface ModuleRequest {
    /**
     * 
     * @type {string}
     * @memberof ModuleRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleRequest
     */
    displayName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModuleRequest
     */
    actions?: Array<string>;
}

/**
 * Check if a given object implements the ModuleRequest interface.
 */
export function instanceOfModuleRequest(value: object): value is ModuleRequest {
    return true;
}

export function ModuleRequestFromJSON(json: any): ModuleRequest {
    return ModuleRequestFromJSONTyped(json, false);
}

export function ModuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'actions': json['actions'] == null ? undefined : json['actions'],
    };
}

export function ModuleRequestToJSON(json: any): ModuleRequest {
    return ModuleRequestToJSONTyped(json, false);
}

export function ModuleRequestToJSONTyped(value?: ModuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'displayName': value['displayName'],
        'actions': value['actions'],
    };
}

