/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface PageResponseUser
 */
export interface PageResponseUser {
    /**
     * 
     * @type {Array<User>}
     * @memberof PageResponseUser
     */
    content?: Array<User>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseUser
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseUser
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseUser
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseUser
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseUser interface.
 */
export function instanceOfPageResponseUser(value: object): value is PageResponseUser {
    return true;
}

export function PageResponseUserFromJSON(json: any): PageResponseUser {
    return PageResponseUserFromJSONTyped(json, false);
}

export function PageResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UserFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseUserToJSON(json: any): PageResponseUser {
    return PageResponseUserToJSONTyped(json, false);
}

export function PageResponseUserToJSONTyped(value?: PageResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UserToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

