/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionRequest
 */
export interface PermissionRequest {
    /**
     * 
     * @type {string}
     * @memberof PermissionRequest
     */
    moduleName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PermissionRequest
     */
    actions?: Array<string>;
}

/**
 * Check if a given object implements the PermissionRequest interface.
 */
export function instanceOfPermissionRequest(value: object): value is PermissionRequest {
    return true;
}

export function PermissionRequestFromJSON(json: any): PermissionRequest {
    return PermissionRequestFromJSONTyped(json, false);
}

export function PermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'moduleName': json['moduleName'] == null ? undefined : json['moduleName'],
        'actions': json['actions'] == null ? undefined : json['actions'],
    };
}

export function PermissionRequestToJSON(json: any): PermissionRequest {
    return PermissionRequestToJSONTyped(json, false);
}

export function PermissionRequestToJSONTyped(value?: PermissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'moduleName': value['moduleName'],
        'actions': value['actions'],
    };
}

