/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleRequest
 */
export interface RoleRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the RoleRequest interface.
 */
export function instanceOfRoleRequest(value: object): value is RoleRequest {
    return true;
}

export function RoleRequestFromJSON(json: any): RoleRequest {
    return RoleRequestFromJSONTyped(json, false);
}

export function RoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function RoleRequestToJSON(json: any): RoleRequest {
    return RoleRequestToJSONTyped(json, false);
}

export function RoleRequestToJSONTyped(value?: RoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

