/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScopeRequest
 */
export interface ScopeRequest {
    /**
     * 
     * @type {string}
     * @memberof ScopeRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeRequest
     */
    displayName?: string;
}

/**
 * Check if a given object implements the ScopeRequest interface.
 */
export function instanceOfScopeRequest(value: object): value is ScopeRequest {
    return true;
}

export function ScopeRequestFromJSON(json: any): ScopeRequest {
    return ScopeRequestFromJSONTyped(json, false);
}

export function ScopeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScopeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
    };
}

export function ScopeRequestToJSON(json: any): ScopeRequest {
    return ScopeRequestToJSONTyped(json, false);
}

export function ScopeRequestToJSONTyped(value?: ScopeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'displayName': value['displayName'],
    };
}

