/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ScopeRepresentation,
  ScopeRequest,
} from '../models/index';
import {
    ScopeRepresentationFromJSON,
    ScopeRepresentationToJSON,
    ScopeRequestFromJSON,
    ScopeRequestToJSON,
} from '../models/index';

export interface CreateScopeRequest {
    scopeRequest: ScopeRequest;
}

/**
 * 
 */
export class PermissionsScopesApi extends runtime.BaseAPI {

    /**
     * Create a new action (scope)
     */
    async createScopeRaw(requestParameters: CreateScopeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScopeRepresentation>> {
        if (requestParameters['scopeRequest'] == null) {
            throw new runtime.RequiredError(
                'scopeRequest',
                'Required parameter "scopeRequest" was null or undefined when calling createScope().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/scopes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScopeRequestToJSON(requestParameters['scopeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScopeRepresentationFromJSON(jsonValue));
    }

    /**
     * Create a new action (scope)
     */
    async createScope(requestParameters: CreateScopeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScopeRepresentation> {
        const response = await this.createScopeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all available scopes
     */
    async getAllScopesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScopeRepresentation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/scopes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScopeRepresentationFromJSON));
    }

    /**
     * Get all available scopes
     */
    async getAllScopes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScopeRepresentation>> {
        const response = await this.getAllScopesRaw(initOverrides);
        return await response.value();
    }

}
