/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModuleRequest,
  ResourceRepresentation,
} from '../models/index';
import {
    ModuleRequestFromJSON,
    ModuleRequestToJSON,
    ResourceRepresentationFromJSON,
    ResourceRepresentationToJSON,
} from '../models/index';

export interface CreateModuleRequest {
    moduleRequest: ModuleRequest;
}

export interface GetModuleByNameRequest {
    moduleName: string;
}

export interface UpdateModuleActionsRequest {
    moduleName: string;
    requestBody: Array<string>;
}

/**
 * 
 */
export class PermissionsModulesApi extends runtime.BaseAPI {

    /**
     * Create a new module (resource)
     */
    async createModuleRaw(requestParameters: CreateModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResourceRepresentation>> {
        if (requestParameters['moduleRequest'] == null) {
            throw new runtime.RequiredError(
                'moduleRequest',
                'Required parameter "moduleRequest" was null or undefined when calling createModule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/modules`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModuleRequestToJSON(requestParameters['moduleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResourceRepresentationFromJSON(jsonValue));
    }

    /**
     * Create a new module (resource)
     */
    async createModule(requestParameters: CreateModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResourceRepresentation> {
        const response = await this.createModuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all available modules
     */
    async getAllModulesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ResourceRepresentation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/modules`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ResourceRepresentationFromJSON));
    }

    /**
     * Get all available modules
     */
    async getAllModules(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ResourceRepresentation>> {
        const response = await this.getAllModulesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a single module by its unique name
     */
    async getModuleByNameRaw(requestParameters: GetModuleByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResourceRepresentation>> {
        if (requestParameters['moduleName'] == null) {
            throw new runtime.RequiredError(
                'moduleName',
                'Required parameter "moduleName" was null or undefined when calling getModuleByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/modules/{moduleName}`;
        urlPath = urlPath.replace(`{${"moduleName"}}`, encodeURIComponent(String(requestParameters['moduleName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResourceRepresentationFromJSON(jsonValue));
    }

    /**
     * Get a single module by its unique name
     */
    async getModuleByName(requestParameters: GetModuleByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResourceRepresentation> {
        const response = await this.getModuleByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the actions (scopes) for a module
     */
    async updateModuleActionsRaw(requestParameters: UpdateModuleActionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['moduleName'] == null) {
            throw new runtime.RequiredError(
                'moduleName',
                'Required parameter "moduleName" was null or undefined when calling updateModuleActions().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateModuleActions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/modules/{moduleName}/actions`;
        urlPath = urlPath.replace(`{${"moduleName"}}`, encodeURIComponent(String(requestParameters['moduleName'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the actions (scopes) for a module
     */
    async updateModuleActions(requestParameters: UpdateModuleActionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateModuleActionsRaw(requestParameters, initOverrides);
    }

}
