/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PermissionRequest,
  RoleRepresentation,
  RoleRequest,
} from '../models/index';
import {
    PermissionRequestFromJSON,
    PermissionRequestToJSON,
    RoleRepresentationFromJSON,
    RoleRepresentationToJSON,
    RoleRequestFromJSON,
    RoleRequestToJSON,
} from '../models/index';

export interface AssignPermissionsToRoleRequest {
    roleName: string;
    permissionRequest: PermissionRequest;
}

export interface CreateRoleRequest {
    roleRequest: RoleRequest;
}

/**
 * 
 */
export class PermissionsRolesApi extends runtime.BaseAPI {

    /**
     * Assign a set of actions on a module to a role
     */
    async assignPermissionsToRoleRaw(requestParameters: AssignPermissionsToRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['roleName'] == null) {
            throw new runtime.RequiredError(
                'roleName',
                'Required parameter "roleName" was null or undefined when calling assignPermissionsToRole().'
            );
        }

        if (requestParameters['permissionRequest'] == null) {
            throw new runtime.RequiredError(
                'permissionRequest',
                'Required parameter "permissionRequest" was null or undefined when calling assignPermissionsToRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/roles/{roleName}/permissions`;
        urlPath = urlPath.replace(`{${"roleName"}}`, encodeURIComponent(String(requestParameters['roleName'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PermissionRequestToJSON(requestParameters['permissionRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Assign a set of actions on a module to a role
     */
    async assignPermissionsToRole(requestParameters: AssignPermissionsToRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.assignPermissionsToRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Create a new role
     */
    async createRoleRaw(requestParameters: CreateRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['roleRequest'] == null) {
            throw new runtime.RequiredError(
                'roleRequest',
                'Required parameter "roleRequest" was null or undefined when calling createRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/roles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RoleRequestToJSON(requestParameters['roleRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new role
     */
    async createRole(requestParameters: CreateRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Get all available roles
     */
    async getAllRolesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoleRepresentation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/roles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoleRepresentationFromJSON));
    }

    /**
     * Get all available roles
     */
    async getAllRoles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleRepresentation>> {
        const response = await this.getAllRolesRaw(initOverrides);
        return await response.value();
    }

}
